set -g mouse on
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1

# rebind prefix
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# vi style copy-pasting
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# style stuff
set -g status-right '#(gitmux) %H:%M %d-%b-%y'
set -g status-right-length 60
set -g status-style 'bg=#333333 fg=#5eacd3'
