#!/bin/sh

# This pre-commit hook is based on: https://ortogonal.github.io/cpp/git-clang-format/

if git rev-parse --verify HEAD >/dev/null 2>&1  
then  
against=HEAD  
else  
# Initial commit: diff against an empty tree object  
against=4b825dc642cb6eb9a060e54bf8d69288fbee4904  
fi 

# Test clang-format  
clangformatout=$(git clang-format --staged --diff -q)
  
# Redirect output to stderr.  
exec 1>&2  
  
if [ "$clangformatout" != "" ]  
then
    echo "Format Error!"
    echo "The new code added contains differences against clang-format rules."
    echo "Use git clang-format --diff --staged to view the necessary changes."
    echo "Use git clang-format to apply the changes."
    exit 1
fi
